# TMN_DataGen/configs/default_preprocessing_config.yaml  
preprocessing:
  strictness_level: 1
  tokenizer: regex
  language: en
  preserve_case: false
  remove_punctuation: true
  normalize_unicode: true
  remove_numbers: false
  max_token_length: 50
  min_token_length: 1
