# TMN_DataGen/configs/default_preprocessing_config.yaml  
preprocessing:
  strictness_level: 2
  tokenizer: regex
  language: en
  preserve_case: false
  remove_punctuation: true
  normalize_unicode: true
  remove_numbers: false
  max_token_length: 30
  min_token_length: 0
  question_types: ['open-ended', 'yes/no']
