# TMN_DataGen/configs/default_parser_config.yaml
parser:
  type: multi
  batch_size: 8000
  diaparser_batch_size: 25000
  spacy_batch_size: 40000
  min_tokens: 3
  max_tokens: 50
  min_nodes: 3
  max_nodes: 50
  parsers:
    diaparser:
      enabled: true
      model_name: en_ewt.electra-base
    spacy:
      enabled: true 
      model_name: en_core_web_sm
  feature_sources:
    tree_structure: diaparser
    pos_tags: spacy
    morph: spacy
    lemmas: spacy
    dependency_labels: diaparser


