# TMN_DataGen/configs/default_config.yaml
parser:
  type: diaparser
  batch_size: 32
  model_name: en_ewt.electra-base
  
feature_extraction:
  word_embedding_model: bert-base-uncased
  use_word_embeddings: true
  use_pos_tags: true
  use_morph_features: false

visualization:
  show_features: false
  
processing:
  max_sequence_length: 128
  lowercase: true

preprocessing:
  strictness_level: 1  # 0-3
  tokenizer: "regex"   # "regex" or "stanza"
  language: "en"
  preserve_case: false
  # Regex preprocessing options  
  remove_punctuation: true
  normalize_unicode: true
  remove_numbers: false
  # Tokenizer specific options
  max_token_length: 50
  min_token_length: 1

verbose: "debug"  # Options: null, "normal", "debug"
