# TMN_DataGen/configs/multi_parser_config.yaml
parser:
  type: multi
  batch_size: 32
  
  parsers:
    diaparser:
      enabled: true
      model_name: en_ewt.electra-base
      batch_size: 32
      feature_map:
        pos_tags:
          source: upos
          target: pos_tag
        dependencies:
          source: deprel
          target: dependency_type
        lemmas:
          source: lemma
          target: lemma
    
    spacy:
      enabled: true
      model_name: en_core_web_trf
      batch_size: 32
      feature_map:
        pos_tags:
          source: pos_
          target: pos_tag
        morph:
          source: morph
          target: morph_features
        lemmas:
          source: lemma_
          target: lemma
        ner:
          source: ent_type_
          target: entity_type
  
  feature_sources:
    tree_structure: diaparser
    pos_tags: spacy
    morph: spacy
    lemmas: spacy
    dependencies: diaparser
    ner: spacy

feature_extraction:
  word_embedding_model: bert-base-uncased
  use_word_embeddings: true
  use_pos_tags: true
  use_morph_features: true
  use_entity_types: true

visualization:
  show_features: true

processing:
  max_sequence_length: 128
  lowercase: true
  merge_subtokens: true

verbose: "debug"  # Options: null, "normal", "debug"
