# configs/preprocessing_strict.yaml
preprocessing:
  strictness_level: 3
  tokenizer: "regex"
  language: "en"
  preserve_case: false
  remove_punctuation: true
  normalize_unicode: true
  remove_numbers: true
  max_token_length: 50
  min_token_length: 2
